version: "3"

services:
  train:
    build: .
    volumes:
      - .:/app
    command: poetry run python -m argument_nli.train
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              # device_ids: ["7"]
              capabilities: ["gpu"]
  deploy:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    command: poetry run python -m argument_nli.deploy ${HOST}:${PORT}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
