[tool.poetry]
name = "Argument-NLI"
version = "0.1.0"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.dependencies]
python = "~3.8"
dynaconf = "^3.1.7"
transformers = "^4.14.1"
datasets = "^1.16.1"
torch = "^1.10.1"
lxml = "^4.7.1"
typer = "^0.4.0"
pandas = "^1.3.5"
arg-services = "^0.1.21"
dataclasses-json = "^0.5.6"
arguebuf = "^0.2.3"
scikit-learn = "^1.0.2"

[tool.poetry.dev-dependencies]
ipykernel = "^6.6.0"
lxml-stubs = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
