[tool.poetry]
name = "Argument-NLI"
version = "0.1.0"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.dependencies]
python = "~3.8"
dynaconf = "^3.1.7"
transformers = "^4.16.2"
datasets = "^2.0.0"
torch = "^1.10.2"
lxml = "^4.7.1"
typer = "^0.7.0"
pandas = "^1.4.1"
arg-services = "^0.3.0"
dataclasses-json = "^0.5.6"
arguebuf = "^1.0.0"
scikit-learn = "^1.0.2"
ordered-set = "^4.1.0"
sentencepiece = "^0.1.96"

[tool.poetry.dev-dependencies]
ipykernel = "^6.9.0"
lxml-stubs = "^0.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
