[tool.poetry]
name = "Argument-NLI"
version = "1.0.0"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.dependencies]
python = "^3.10"
dynaconf = "^3.1.12"
transformers = "^4.30.2"
datasets = "^2.13.0"
torch = "^2.0.1"
lxml = "^4.9.2"
typer = "^0.9.0"
pandas = "^2.0.2"
arg-services = "^1.3.2"
arguebuf = { version = "^2.0.0b25", allow-prereleases = true }
scikit-learn = "^1.2.2"
stableset = "^5.2.1"

[tool.poetry.dev-dependencies]
lxml-stubs = "^0.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
