[convert]
random_state = 0
include_neutral = false
neutral_distance = 25

[model]
path = "data/model.pt"
pretrained = "microsoft/deberta-v3-base"
device = "cpu"
max_sequence_length = 512

[model.train]
dataset_path = "data"
dataset_pattern = "*.pickle"
batch_size = 128
epochs = 5
learning_rate = 0.00002
