[convert]
random_state = 0

[model]
path = "data/model.pt"
dataset_path = "data"
dataset_pattern = "*.pickle"
pretrained = "bert-base-uncased"
device = "cpu"
batch_size = 128
max_sequence_length = 512
epochs = 3
learning_rate = 0.00002

[grpc]
