[convert]
random_state = 0
neutral_distance = 25

[model]
path = "data/model.pt"
pretrained = "microsoft/deberta-v3-base"
batch_size = 16
max_sequence_length = 512
dataloader_workers = 4
include_neutral = true

[model.train]
dataset_path = "data"
dataset_pattern = "*.pickle"
warmup_steps = 10
max_epochs = 5
learning_rate = 0.00002
