[path]
model = "data/model.pt"
datasets = [
    "data/araucaria.json.gz",
    "data/kialo.json.gz",
    "data/pheme.json.gz",
]

[convert]
random_state = 0

[model]
pretrained = "bert-base-uncased"
device = "cpu"
batch_size = 2048
max_sequence_length = 512
epochs = 6
learning_rate = 0.0003

[grpc]
